In [8]:
from sklearn.datasets import make_regression
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go

from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [27]:
X,y=make_regression(n_samples=100,n_features=2 ,n_informative=2,n_targets=1,noise=10)

In [28]:
df = pd.DataFrame({'feature1':X[:,0],'feature2':X[:,1],'target':y})

In [29]:
df.head()

feature1  feature2      target
0  0.678718 -0.219148   31.553992
1  0.853297 -0.863294   10.403638
2 -0.050209 -1.642780  -95.470380
3 -0.955906  0.331707  -52.044119
4  2.412835 -0.157267  147.275945

In [30]:
fig=px.scatter_3d(df,x='feature1',y='feature2',z='target')
fig.show()

In [31]:
from sklearn.model_selection import cross_val_score, train_test_split,KFold
from sklearn.linear_model import LinearRegression
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=3)

In [32]:
lr=LinearRegression()

In [33]:
lr.fit(X_train,y_train)

LinearRegression()

In [34]:
kf=KFold(n_splits=25,shuffle=True,random_state=2)
score=cross_val_score(lr,X_train,y_train,cv=kf)

In [35]:
print(f'Cross_validation_score of train dataset:{np.mean(score)*100}')

Cross_validation_score of train dataset:94.95898514750242


In [36]:
pred_reg=lr.predict(X_test)

In [38]:
print('Mean Absolute Error:',mean_absolute_error(y_test, pred_reg))
print('Mean Squared Error:',mean_squared_error(y_test, pred_reg))
print('Root Mean Squared Error:',np.sqrt(mean_squared_error(y_test, pred_reg)))
score=r2_score(y_test,pred_reg)
print(f"Test score:{score*100}")

Mean Absolute Error: 8.023440417783677
Mean Squared Error: 93.07638622808437
Root Mean Squared Error: 9.647610389525708
Test score:98.0839867623922


In [46]:
x = np.linspace(-5,5, 10)
y = np.linspace(-5,5, 10)
xGrid, yGrid = np.meshgrid(y, x)

final = np.vstack((xGrid.ravel().reshape(1,100),yGrid.ravel().reshape(1,100))).T
z_final = lr.predict(final).reshape(10,10)
z = z_final

In [47]:
fig=px.scatter_3d(df, x='feature1', y='feature2', z='target')
fig.add_trace(go.Surface(x=x,y=y,z=z))
fig.show()

In [48]:
lr.coef_

array([63.07463042, 48.15315849])

In [49]:
lr.intercept_

-1.1238594634134582

##`Making our own Linear Regression Class`

In [29]:
import numpy as np
from sklearn.datasets import load_diabetes

In [30]:
X,y=load_diabetes(return_X_y=True)

In [31]:
X.shape

(442, 10)

In [32]:
y.shape

(442,)

In [33]:
from sklearn.model_selection import cross_val_score, train_test_split,KFold
from sklearn.linear_model import LinearRegression
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=3)

In [34]:
print(X_train.shape)
print(X_test.shape)

(353, 10)
(89, 10)


In [35]:
lr=LinearRegression()

In [36]:
lr.fit(X_train,y_train)

LinearRegression()

In [37]:
kf=KFold(n_splits=25,shuffle=True,random_state=2)
score=cross_val_score(lr,X_train,y_train,cv=kf)

In [38]:
print(f'Cross_validation_score of train dataset:{np.mean(score)*100}')

Cross_validation_score of train dataset:44.58764646336485


In [39]:
pred_reg=lr.predict(X_test)
pred_reg[0]

99.48235947401687

In [40]:
lr.coef_

array([  -1.13744712, -212.8867836 ,  540.45536994,  345.20621542,
       -938.23814645,  516.62060367,  172.85885498,  267.87535242,
        732.63230159,   70.07849485])

In [41]:
lr.intercept_

153.13441535285003

In [42]:
class meraMLR:
  def __init__(self):
    self.coff_=None
    self.intercept_=None
  def fit(self,X_train,y_train):
    X_train=np.insert(X_train,0,1,axis=1)
    # calc cofficient
    betas=np.linalg.inv(np.dot((np.transpose(X_train)),X_train)).dot(np.transpose(X_train)).dot(y_train)
    self.intercept_=betas[0]
    self.coff_=betas[1:]
  def prediction(self,X_test):
    y_pred=np.dot(X_test,self.coff_)+self.intercept_
    return y_pred

In [43]:
Mlr=meraMLR()

In [44]:
Mlr.fit(X_train,y_train)

In [46]:
Mlr.prediction(X_test)[0]

99.482359474017

In [47]:
Mlr.coff_

array([  -1.13744712, -212.8867836 ,  540.45536994,  345.20621542,
       -938.23814645,  516.62060367,  172.85885498,  267.87535242,
        732.63230159,   70.07849485])

In [48]:
Mlr.intercept_

153.13441535285006